#!/usr/bin/env node
// Test apps through the checker mu, outputs held against the whitepaper:
//   Thm 2 (HATEOAS): the affordances from a status are exactly the
//     effective transitions — served by the canon's system:view_menu.
//   Thm 1 (validate): an alethic uniqueness violation is flagged with
//     its violating rows (refusal); a clean population passes; the
//     mandatory family answers violations by set difference.
//   Def derive / Lem 1: a derivation rule is a projection of a natural
//     join over settled facts — grandparenthood computed as a theta
//     composition, terminating, inventing no atoms (adom preserved).
//   RMAP per app: a normal multi-entity app absorbs into one cell per
//     entity (Def 8), m:n fact types separate.
//
//   node test-apps.js       (expects apps/*/design-state generated by
//                            the oracle over each app's .combined dir)
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..", "..");

// ---- vocabulary + mu (the checker's, verbatim) ----
const DEFS = Object.create(null);
const DEF = (n, t) => { DEFS[n] = t; return t; };
const A = x => x;
const N = x => x;
const K = x => ["CONST", x];
const PHI = () => [];
const mk = n => (...a) => {
  if (a.length !== n) throw new Error("S" + n + " got " + a.length);
  return a;
};
const S1 = mk(1), S2 = mk(2), S3 = mk(3), S4 = mk(4), S5 = mk(5),
      S6 = mk(6), S7 = mk(7), S8 = mk(8), S9 = mk(9);
eval(fs.readFileSync(path.join(root, "arest"), "utf8"));

const isSeq = Array.isArray;
function deepEq(a, b) {
  if (a === b) return true;
  if (!isSeq(a) || !isSeq(b) || a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (!deepEq(a[i], b[i])) return false;
  return true;
}
const prims = {
  "id": x => x,
  "tl": x => x.slice(1),
  "atom": x => (isSeq(x) ? "F" : "T"),
  "apndl": ([x, ys]) => [x, ...ys],
  "apndr": ([xs, y]) => [...xs, y],
  "distl": ([x, ys]) => ys.map(y => [x, y]),
  "distr": ([xs, y]) => xs.map(x => [x, y]),
  "cat": ([xs, ys]) => [...xs, ...ys],
  "null": x => (isSeq(x) && x.length === 0 ? "T" : "F"),
  "eq": ([a, b]) => (deepEq(a, b) ? "T" : "F"),
  "not": b => (b === "T" ? "F" : "T"),
  "and": ([a, b]) => (a === "T" && b === "T" ? "T" : "F"),
  "length": x => x.length,
  "le": ([a, b]) => (a <= b ? "T" : "F"),
  "ge": ([a, b]) => (a >= b ? "T" : "F"),
  "gt": ([a, b]) => (a > b ? "T" : "F"),
  "+": ([a, b]) => a + b,
  "apply": ([f, x]) => ev(f, x),
};
function ev(f, x) {
  if (typeof f === "number") {
    if (!isSeq(x)) throw new Error("selector " + f + " on non-sequence");
    return x[f - 1];
  }
  if (typeof f === "string") {
    if (Object.prototype.hasOwnProperty.call(prims, f)) return prims[f](x);
    if (f in DEFS) return ev(DEFS[f], x);
    throw new Error("unresolved atom '" + f + "'");
  }
  if (isSeq(f)) {
    switch (f[0]) {
      case "COMP": { let v = x; for (let i = f.length - 1; i >= 1; i--) v = ev(f[i], v); return v; }
      case "CONS": return f.slice(1).map(g => ev(g, x));
      case "CONST": return f[1];
      case "COND": return ev(f[1], x) === "T" ? ev(f[2], x) : ev(f[3], x);
      case "ALPHA": return x.map(e => ev(f[1], e));
      case "INSERT": {
        if (!isSeq(x) || x.length === 0) throw new Error("INSERT over empty");
        let acc = x[x.length - 1];
        for (let i = x.length - 2; i >= 0; i--) acc = ev(f[1], [x[i], acc]);
        return acc;
      }
      case "WHILE": { let v = x; while (ev(f[1], v) === "T") v = ev(f[2], v); return v; }
      default: throw new Error("unhandled form head: " + JSON.stringify(f[0]));
    }
  }
  throw new Error("unevaluable: " + JSON.stringify(f));
}

// ---- carriers ----
const flat1 = x => ev("theta:flatten", x);
function unfold(x, leaf) {
  if (!isSeq(x) || x.length === 0) return x;
  let v = x;
  while (!v.every(leaf)) v = flat1(v);
  return v;
}
const isAtom = e => !isSeq(e);
const isRow = e => isSeq(e) && e.length > 0 && e.every(isAtom);
const isDesc = e => isSeq(e) && e.length === 5 && isAtom(e[0]) && isSeq(e[1]);
const isPair = e => isSeq(e) && e.length === 2 && isAtom(e[0]);

function loadApp(app) {
  const dir = path.join(root, "apps", app);
  const local = Object.create(null);
  const env = { DEF: (n, t) => { local[n] = t; }, A, N, K, PHI, S1, S2, S3, S4, S5, S6, S7, S8, S9 };
  const keys = Object.keys(env);
  const vals = keys.map(k => env[k]);
  for (const f of ["design-state", "norma-answer"]) {
    const src = fs.readFileSync(path.join(dir, f), "utf8");
    new Function(...keys, "return (" + src.replace(/^\(/, "").replace(/\)\s*$/, "") + ");")(...vals);
  }
  const fts = unfold(local["state:fts"], isDesc).map(d => [d[0], d[1], d[2], d[3], unfold(d[4], isRow)]);
  const tables = unfold(local["norma:tables"], isPair).map(t => ({ name: t[0], columns: unfold(t[1], isAtom) }));
  const rows = name => {
    const d = fts.find(e => e[0] === name);
    return d ? d[4] : null;
  };
  return { fts, tables, rows };
}

// ---- claims ----
const results = [];
function claim(app, name, ok, detail) {
  results.push([app, name, ok, detail || ""]);
}

// ===================== sale app =====================
{
  const sale = loadApp("order");

  // Thm 2: affordances = effective transitions, via system:view_menu
  const defIn = sale.rows("TransitionIsDefinedInStateMachineDefinition") || [];
  const from = new Map((sale.rows("TransitionIsFromStatus") || []).map(r => [r[0], r[1]]));
  const to = new Map((sale.rows("TransitionIsToStatus") || []).map(r => [r[0], r[1]]));
  const trig = new Map((sale.rows("TransitionIsTriggeredByEventType") || []).map(r => [r[0], r[1]]));
  const triples = defIn.filter(r => r[1] === "Sale")
    .map(r => [from.get(r[0]), trig.get(r[0]), to.get(r[0])]);
  const expect = {
    "draft": [["Sale is submitted", "placed"]],
    "placed": [["Sale is paid for", "paid"], ["Sale is cancelled", "cancelled"]],
    "paid": [["Sale is shipped", "shipped"]],
    "shipped": [],
    "cancelled": [],
  };
  let thm2 = true, thm2detail = [];
  for (const status of Object.keys(expect)) {
    const menu = ev("system:view_menu", [status, triples]);
    const got = menu[1].map(b => [b[1], b[2]]).sort();
    const want = expect[status].sort();
    if (!deepEq(got, want)) { thm2 = false; thm2detail.push(status + ": got " + JSON.stringify(got)); }
  }
  claim("sale", "Thm 2: view_menu affordances = effective transitions per status (5 statuses)", thm2, thm2detail.join("; "));

  // Thm 1 validate: uniqueness refusal on a duplicated key, clean pass on P
  const totals = sale.rows("SaleHasTotal");
  let ucSpec = null, ucViol = null;
  for (const spec of [[1], 1, [["CONS", 1]], ["CONS", 1]]) {
    try {
      const checker = ev("apply", ["constraints:uniqueness", spec]);
      const bad = [...totals, ["o1", "7.77"]];
      const v = ev("apply", [checker, bad]);
      if (isSeq(v) && v.length > 0) {
        const clean = ev("apply", [checker, totals]);
        if (isSeq(clean) && clean.length === 0) { ucSpec = spec; ucViol = v; break; }
      }
    } catch (e) { /* next spec */ }
  }
  claim("sale", "Thm 1: alethic UC refuses the duplicated key, passes clean P",
    ucSpec !== null,
    ucSpec !== null ? "key spec " + JSON.stringify(ucSpec) + ", violations " + JSON.stringify(ucViol) : "no operand shape produced a discriminating checker");

  // Thm 1 mandatory family: violations by set difference
  const saleIds = ["o1", "o2", "o3", "o4"];
  const placed = (sale.rows("SaleIsPlacedByCustomer") || []).map(r => r[0]);
  const mand = ev("constraints:mandatory", [saleIds, placed]);
  claim("sale", "Thm 1: mandatory violation = set difference (injected o4 unplaced)",
    deepEq(mand, ["o4"]), JSON.stringify(mand));

  // RMAP per app (Def 8): entity absorption + m:n separation
  const saleTable = sale.tables.find(t => t.name === "Sale");
  const ternary = sale.tables.find(t => t.name === "SaleContainsItemInQuantity");
  claim("sale", "RMAP: Sale absorbs its functional facts (customer FK, unary booleans, total)",
    !!saleTable && saleTable.columns.includes("customerNr") && saleTable.columns.includes("total"),
    saleTable ? saleTable.columns.join(",") : "no Sale table");
  claim("sale", "RMAP: the m:n ternary separates", !!ternary, ternary ? ternary.columns.join(",") : "missing");
}

// ===================== family app =====================
{
  const fam = loadApp("family");
  const parent = fam.rows("PersonIsParentOfPerson");
  claim("family", "population attributed (4 parent rows)", parent && parent.length === 4,
    JSON.stringify(parent));

  // Def derive / Lem 1: grandparent as a theta composition — a projection
  // of the natural join of parentOf with itself, deduplicated
  const pred = ["COMP", "eq", ["CONS", ["COMP", 2, 1], ["COMP", 1, 2]]];
  const keep = ["COND", ["COMP", pred, 1], "apndl", 2];
  const filterMatches = ["COMP", ["INSERT", keep], "theta:append_phi", "distl"];
  const emit = ["CONS", ["COMP", 1, 1], ["COMP", 2, 2]];
  const inner = ["COMP", ["ALPHA", emit], filterMatches];
  const grandparent = ["COMP", "theta:dedup", "theta:flatten", ["ALPHA", inner], "distr", ["CONS", "id", "id"]];
  const gp = ev(grandparent, parent);
  const want = [["alice", "carol"], ["alice", "dave"], ["bob", "erin"]];
  const sortPairs = xs => [...xs].sort((a, b) => (a[0] + a[1]).localeCompare(b[0] + b[1]));
  claim("family", "Def derive: grandparent = Project(NatJoin(parent, parent)), exact rows",
    deepEq(sortPairs(gp), sortPairs(want)), JSON.stringify(gp));

  // Lem 1: no atom invention — every derived atom is in adom(P)
  const adom = new Set(parent.flat());
  claim("family", "Lem 1: derivation invents no atoms (adom preserved)",
    gp.flat().every(a => adom.has(a)));

  // the ring constraint built from "No Person is parent of itself"
  const report = fs.readFileSync(path.join(root, "apps", "family", "oracle-report.txt"), "utf8");
  claim("family", "ring constraint (irreflexive) built by NORMA from the No-form",
    /ring constraint \(irreflexive\)/.test(report));
  claim("family", "RMAP: the ring m:n keeps its own table",
    fam.tables.some(t => t.name === "PersonIsParentOfPerson"));
}

// ---- report ----
let failed = 0;
console.log("whitepaper claims through the checker mu:");
for (const [app, name, ok, detail] of results) {
  console.log("  " + (ok ? "PASS" : "FAIL") + "  [" + app + "] " + name + (ok || !detail ? "" : " — " + detail));
  if (!ok) failed++;
}
console.log(failed === 0 ? "ALL CLAIMS HOLD (" + results.length + ")" : failed + " CLAIM(S) FAILED of " + results.length);
if (failed > 0) process.exitCode = 1;
