# -*- coding: utf-8 -*-
# THE PROCEDURAL TRANSFORM, js target: the canon's forms are a GRAMMAR
# (Backus never said lambda) - this emits each DEF as a procedural js
# function. COMP nests calls, CONS builds arrays, COND is ?:, ALPHA
# maps, INSERT right-folds, WHILE loops, selectors index - all through
# the head's own strictness helpers so refusals refuse identically.
# DEF-to-DEF calls are DIRECT (the DEFS lookup vanishes); registered
# names resolve at call time through PRIMS (the boundary intact); the
# tree-walking Ev survives as the rho-fallback for terms that arrive
# as DATA (apply of store-held representations), and the patch makes
# Ev dispatch compiled functions first - so dynamic application of a
# DEF name lands in native code too.
import io, json, re

CANON = r"C:\Users\lippe\Repos\arest\arest"
OUT = r"C:\Users\lippe\AppData\Local\Temp\claude\C--Users-lippe-Repos\d47c55b5-df4a-48cb-b323-238b7f78fa4b\scratchpad\compiled.part.js"
env = {}
exec(io.open("mu_bench_head.py", encoding="utf-8").read(), env)
eval(compile(io.open(CANON, encoding="utf-8").read(), CANON, "eval"), env)
DEFS = env["DEFS"]

names = sorted(DEFS.keys())
fid = {n: "d%d" % i for i, n in enumerate(names)}

def jslit(v):
    if isinstance(v, tuple):
        return "[" + ",".join(jslit(e) for e in v) + "]"
    if isinstance(v, int):
        return str(v)
    return json.dumps(v)

def emit(t, x):
    # compile term t applied to js expression x
    if isinstance(t, int):
        return "S(%s,%d)" % (x, t)
    if isinstance(t, str):
        if t in fid:
            return "%s(%s)" % (fid[t], x)
        return "P(%s,%s)" % (json.dumps(t), x)
    if len(t) == 0:
        raise AssertionError("empty form")
    h = t[0]
    if h == "CONST":
        return "K%d" % konst(t[1])
    if h == "COMP":
        e = x
        for part in reversed(t[1:]):
            e = emit(part, e)
        return e
    if h == "CONS":
        return "[" + ",".join(emit(p, x) for p in t[1:]) + "]"
    if h == "COND":
        return "(%s===\"T\"?%s:%s)" % (
            emit(t[1], x), emit(t[2], x), emit(t[3], x))
    if h == "ALPHA":
        return "seq(%s).map(_e=>%s)" % (x, emit(t[1], "_e"))
    if h == "INSERT":
        return "FOLD(%s,(_a,_b)=>%s)" % (x, emit(t[1], "[_a,_b]"))
    if h == "WHILE":
        return "WH(%s,_v=>%s,_v=>%s)" % (
            x, emit(t[1], "_v"), emit(t[2], "_v"))
    raise AssertionError("unknown form head: %r" % (h,))

konsts = []
def konst(v):
    konsts.append(v)
    return len(konsts) - 1

lines = []
lines.append(";")
lines.append("// GENERATED by transform_js.py - the procedural projection of the")
lines.append("// canon. Every DEF below is a js function; the tree-walking Ev")
lines.append("// remains the rho-fallback for terms arriving as data, patched to")
lines.append("// dispatch compiled functions first.")
lines.append("(function(){")
lines.append("const S=(x,n)=>{if(!Array.isArray(x))throw new Error(\"selector \"+n+\" on atom: \"+x);if(n<1||n>x.length)throw new Error(\"selector \"+n+\" out of range \"+x.length);return x[n-1];};")
lines.append("const P=(n,x)=>{const c=COMPILED[n];if(c)return c(x);if(PRIMS.has(n))return PRIMS.get(n)(x);throw new Error(\"unresolved atom: \"+n);};")
lines.append("const FOLD=(x,f)=>{const a=seq(x);if(a.length===0)throw new Error(\"INSERT on empty\");let acc=a[a.length-1];for(let i=a.length-2;i>=0;i--)acc=f(a[i],acc);return acc;};")
lines.append("const WH=(v,p,f)=>{while(p(v)===\"T\")v=f(v);return v;};")
lines.append("const COMPILED=Object.create(null);")
body = []
for n in names:
    try:
        e = emit(DEFS[n], "x")
        body.append("function %s(x){return %s;}" % (fid[n], e))
        body.append("COMPILED[%s]=%s;" % (json.dumps(n), fid[n]))
    except AssertionError as ex:
        body.append("// SKIPPED %s: %s" % (n, ex))
for i, v in enumerate(konsts):
    lines.append("const K%d=%s;" % (i, jslit(v)))
lines += body
lines.append("const EvTree=Ev;")
lines.append("Ev=function(f,x){if(typeof f===\"string\"){const c=COMPILED[f];if(c)return c(x);}return EvTree(f,x);};")
lines.append("globalThis.__COMPILED_COUNT=Object.keys(COMPILED).length;")
lines.append("})();")
io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print("emitted %d compiled defs, %d consts" % (len(names), len(konsts)))
