// Compile the relational map once and write it beside the store.
//
// rmap is a migration script. Canon already says so: 33 of its steps are
// written as `COND (ast:fetch("stored:rmap:X", store) == '#') -> derive, else
// the stored cell` -- compile once, read thereafter. All 64 references to
// those names are READS. Nothing had ever written one, so every boot and every
// law report rebuilt the whole map: 76.8s on the oracle store, of which
// rmap:colnames alone is 63.6s, and auto.dev never finished a law report at
// all.
//
// This is the writer. It boots a host over the carriers, evaluates each
// artifact once, and emits them as a `compiled` carrier that build.js splices
// alongside design-state and norma-answer. A store that carries it skips the
// derivation entirely.
//
// Generated carriers may use the variadic S(, which the rust build rewrites to
// fixed arity and the js host gets for free from `arguments`. Hand-written
// canon may not -- S1..S9 is the ceiling there -- which is why this emits a
// carrier and not canon.
import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

const here = import.meta.dir;
const root = join(here, "..");
const carriers = process.env.AREST_CARRIERS || join(here, "norma-oracle");

// the artifact names are canon's own, not a list kept in step by hand
const names = [...new Set(
  readFileSync(join(root, "arest"), "utf8").match(/stored:rmap:[a-z_0-9]+/g) || [])].sort();
if (names.length === 0) {
  console.error("no stored:rmap:* names found in canon");
  process.exit(1);
}

await import("file://" + join(here, "js-runner", "cases.g.js").replace(/\\/g, "/"));
const { Ev, CELLS } = globalThis.AREST;

// A("...") carries no escape -- an embedded quote ends the string and a newline
// ends the line -- so a value holding either cannot be emitted, and emitting it
// anyway would produce a carrier that parses as something else. Refuse instead.
function src(v) {
  if (Array.isArray(v)) return v.length === 0 ? "PHI()" : "S(" + v.map(src).join(", ") + ")";
  if (typeof v === "number") return "N(" + v + ")";
  const s = String(v);
  if (s.includes('"') || s.includes("\n") || s.includes("\r")) {
    throw new Error("value is not emittable as canon source: " + JSON.stringify(s.slice(0, 60)));
  }
  return 'A("' + s + '")';
}

const parts = [];
let derived = 0, skipped = 0;
for (const full of names) {
  const step = full.replace(/^stored:/, "");        // stored:rmap:tables -> rmap:tables
  const t = Date.now();
  let v;
  try {
    v = Ev(step, CELLS);
  } catch (e) {
    console.error("  skip " + full + " (" + step + " raised: " + e.message.slice(0, 60) + ")");
    skipped++;
    continue;
  }
  let text;
  try {
    text = src(v);
  } catch (e) {
    console.error("  skip " + full + " (" + e.message + ")");
    skipped++;
    continue;
  }
  parts.push('DEF("' + full + '", ' + text + ")");
  derived++;
  console.error("  " + full.padEnd(28) + String(Date.now() - t).padStart(7) + " ms  " +
    (Array.isArray(v) ? v.length + " rows" : "scalar"));
}

const note = '"THE COMPILED RELATIONAL MAP (generated by tools/compile-rmap.js; regenerate, never edit). One DEF per stored:rmap artifact. Canon reads each through a COND that derives only when the cell is absent, so a store carrying this file skips the Rmap derivation entirely -- 76.8s on the oracle store when it was absent, of which rmap:colnames was 63.6s. This is the migration output: rmap runs for uncompiled schemas and not otherwise. It is keyed to the schema it was compiled from, so a schema change must regenerate it."';

const out = "(\n" + note + ",\n\n" + parts.join(",\n\n") + "\n)\n";
writeFileSync(join(carriers, "compiled"), out);
console.error(derived + " artifacts written, " + skipped + " skipped -> " + join(carriers, "compiled") + " (" + out.length + " bytes)");
