"""Write a store as a DATABASE, and read it back, so the JSON can go.

base.store.json is 3,374,166 bytes of which 92.6% is compiled program -- 906
term cells, every head COMP -- against 59 cells of facts. The program is
regenerated by a compile; the facts are relations. So the store should be a
.db and the JSON should not exist.

The projection already gives every DECLARED fact type a table, and
system.catalog_cells now puts the metamodel's own facts into the fact types the
model declares for them. What is left over is the host encoding -- role,
constraint, spans, factType, instanceOf, refMode, subtype and the rule cells --
which are row-valued but are not fact types, so RMAP gives them no table.

Those are the system catalogue in the literal sense: sqlite_master is not a
user table either. They get one table each under a reserved prefix, with
positional columns, which is mechanical and lossless and -- the point -- makes
them queryable instead of opaque.

    python tools/storedb.py write <store.json> <out.db>
    python tools/storedb.py check <store.json> <out.db>

check is the only part that matters: every fact cell read back out of the
database must equal the cell that went in. A store that does not round-trip is
not a store, it is a hope.
"""
import importlib.util
import json
import os
import re
import sqlite3
import sys

PREFIX = "meta_"


def load(root):
    spec = importlib.util.spec_from_file_location(
        "pyarest", os.path.join(root, "engine", "python", "__init__.py"),
        submodule_search_locations=[os.path.join(root, "engine", "python")])
    mod = importlib.util.module_from_spec(spec)
    sys.modules["pyarest"] = mod
    spec.loader.exec_module(mod)
    return mod


def is_term(v):
    return isinstance(v, list) and v and isinstance(v[0], str)


def fact_cells(path):
    raw = json.load(open(path, encoding="utf-8"))
    return [(c[1], c[2]) for c in raw["d"] if not is_term(c[2])]


def q(n):
    return '"%s"' % str(n).replace('"', '""')


def write(cells, db):
    """One table per cell, positional columns, widest row wins -- and repeating
    groups decomposed into their own table.

    Rows are ragged here: a mandatory constraint carries five elements where a
    uniqueness carries four, so the table is as wide as the widest row and
    short rows leave NULLs, which read back as absent rather than as empty.

    NINE ROWS OF 509 IN `constraint` CARRY A LIST where the others carry a
    value: a deontic prohibition's literals, ["and"] or ["Deontic","Alethic"].
    That is a repeating group, and a repeating group in a store is an
    unmodelled fact type -- Codd's first normal form is the whole argument.
    Rather than serialise it back to JSON in a column, which is the thing being
    removed, the group becomes a child table <cell>_cN of <parent key, value>
    and the parent cell keeps a NULL there. Migrating to tables FOUND this; it
    was invisible while the store was a document.
    """
    con = sqlite3.connect(db)
    n = 0
    for name, rows in cells:
        if not rows:
            continue
        width = max(len(r) for r in rows)
        listcols = {i for r in rows for i, x in enumerate(r)
                    if isinstance(x, list)}
        cols = ["c%d" % (i + 1) for i in range(width)]
        t = PREFIX + name
        con.execute("DROP TABLE IF EXISTS %s" % q(t))
        con.execute("CREATE TABLE %s (%s)"
                    % (q(t), ", ".join(q(c) + " TEXT" for c in cols)))
        flat = []
        for r in rows:
            row = list(r) + [None] * (width - len(r))
            flat.append(tuple(None if isinstance(x, list) else x for x in row))
        con.executemany(
            "INSERT INTO %s VALUES (%s)" % (q(t), ",".join("?" * width)), flat)
        n += len(rows)
        for i in sorted(listcols):
            ct = "%s%s_c%d" % (PREFIX, name, i + 1)
            con.execute("DROP TABLE IF EXISTS %s" % q(ct))
            con.execute("CREATE TABLE %s (parent TEXT, pos INTEGER, value TEXT)"
                        % q(ct))
            child = []
            for r in rows:
                if i < len(r) and isinstance(r[i], list):
                    for j, v in enumerate(r[i]):
                        child.append((r[0], j, v))
            con.executemany("INSERT INTO %s VALUES (?,?,?)" % q(ct), child)
            n += len(child)
    con.commit()
    con.close()
    return n


def read(db):
    """Cells back out, repeating groups reassembled from their child table."""
    con = sqlite3.connect(db)
    tabs = [t for (t,) in con.execute(
        "select name from sqlite_master where type='table' and name like ?",
        (PREFIX + "%",))]
    children = {}
    for t in tabs:
        if re.search(r"_c\d+$", t):
            base, _, col = t.rpartition("_c")
            grp = {}
            for parent, pos, value in con.execute(
                    "SELECT parent, pos, value FROM %s ORDER BY parent, pos" % q(t)):
                grp.setdefault(parent, []).append(value)
            children.setdefault(base[len(PREFIX):], {})[int(col)] = grp
    out = {}
    for t in tabs:
        if re.search(r"_c\d+$", t):
            continue
        name = t[len(PREFIX):]
        rows = con.execute("SELECT * FROM %s" % q(t)).fetchall()
        kids = children.get(name, {})
        made = []
        for r in rows:
            row = list(r)
            for col, grp in kids.items():
                # ONLY the rows that had a group. Reassembling into every row
                # gave the 500 flat constraint rows an empty list where their
                # real value was, which is a data loss that round-trips as a
                # difference rather than as an error.
                if row[0] in grp:
                    row[col - 1] = grp[row[0]]
            made.append(tuple(x for x in row if x is not None))
        out[name] = made
    con.close()
    return out


def main(argv):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if len(argv) < 4:
        print(__doc__.strip().splitlines()[-6])
        return 2
    verb, src, db = argv[1], argv[2], argv[3]
    cells = fact_cells(src)
    if verb == "write":
        n = write(cells, db)
        print("%d cells, %d rows -> %s (%d bytes; json is %d)"
              % (len(cells), n, os.path.basename(db), os.path.getsize(db),
                 os.path.getsize(src)))
        return 0

    write(cells, db)
    back = read(db)

    def norm(rows):
        return sorted(tuple(str(x) for x in r) for r in rows)

    same = differ = missing = 0
    bad = []
    for name, rows in cells:
        if not rows:
            continue
        if name not in back:
            missing += 1
            bad.append(name)
        elif norm(back[name]) == norm(rows):
            same += 1
        else:
            differ += 1
            bad.append(name)
    print("cells with rows: %d   round-trip equal: %d   differ: %d   missing: %d"
          % (same + differ + missing, same, differ, missing))
    if bad:
        print("  problems: %s" % bad[:6])
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
